name: Policy Snapshot Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  SchemaValidation:
    strategy:
      matrix:
        dbversion: [ "postgres:latest" ]
        go: [ "1.17" ]
        platform: [ ubuntu-latest ] # can not run in macOS and widnowsOS
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: ${{ matrix.dbversion }}
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code into the policy directory
        uses: actions/checkout@v2

      - name: Download Cloudquery
        run: |
          curl -L https://github.com/cloudquery/cloudquery/releases/latest/download/cloudquery_Linux_x86_64 -o cloudquery
          chmod a+x cloudquery
      - name: Build Schema
        run: |
          ./cloudquery provider build-schema --config ./test/policy_cq_config.hcl --enable-console-log
        env:
          CQ_NO_TELEMETRY: 1

      - name: Run Snapshot Tests
        run: |
          ./cloudquery policy test ../aws test/snapshot-data --config ./test/policy_cq_config.hcl --enable-console-log
        env:
          CQ_NO_TELEMETRY: 1